FROM jitsi/jicofo:stable

# RUN apt-get update && apt-get install -y python3 python3-pip python3-venv && rm -rf /var/lib/apt/lists/*
# RUN python3 -m venv /venv
# ENV PATH="/venv/bin:$PATH"
# RUN pip install hocon

# COPY edit_hocon.py /edit_hocon.py
COPY jicofo-init.sh /jicofo-init.sh
RUN chmod +x /jicofo-init.sh

ENTRYPOINT ["/jicofo-init.sh"]
